### ISSUE TITLE
logo LodView

### ISSUE THREAD

**Issue by dvcama** [g0v-it/data-inps#1]
salve a tutti, 
siamo molto felici che abbiate scelto lodview per la pubblicazione dei vostri dati ma preferiremmo che il nostro logo nell'header non venisse manipolato e modificato in alcun modo

vi pregheremmo quindi di usare il logo così come da noi immaginato o di sostituirlo a favore di qualcosa di diverso, mantenendo il logo originale lodview nel footer

**Comment by ecow** [comment]
Abbiamo fatto questa scelta  per mantenere il legame con il vostro progetto.

Avevo capito che il vostro materiale è soggetto a licenza open quindi
modificabile purchè con le dovute attribuzioni. Comunque faremo come
chiedete.

Ho però  necessità di capire se ci sono altre limitazioni di licenza o
d'uso e dove si trovano.

enrico


Il dom 9 dic 2018, 20:59 Diego Valerio Camarda <notifications@github.com>
ha scritto:

**Comment by dvcama** [comment]
Il progetto è open source, il logo no, tutto qui, in tutti questi anni
nessuno si è mai indignato per questo e parlo di decine e decine di
installazioni in tutto il mondo

Non ci sono altre limitazioni, per mantenere l'attribuzione è sufficiente
il logo nel footer

Grazie mille

**Comment by ecow** [comment]
Sentiamoci via mail  enrico@linkeddata.center
